---
repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - name: go fmt
        id: go-fmt-repo
      - name: go vet
        id: go-vet-repo-mod
      - name: go build
        id: go-build-repo-mod
      - name: go mod tidy
        id: go-mod-tidy-repo
      - name: golangci-lint
        id: golangci-lint-repo-mod
  - repo: local
    hooks:
      - name: go fix
        id: go-fix
        entry: go fix ./...
        language: system
        pass_filenames: false
      - name: govulncheck
        id: govulncheck
        entry: go tool govulncheck ./...
        language: system
        pass_filenames: false
      - name: gosec
        id: gosec
        entry: go tool gosec -quiet ./...
        language: system
        pass_filenames: false
      - name: staticcheck
        id: staticcheck
        entry: go tool staticcheck ./...
        language: system
        pass_filenames: false
      - name: deadcode
        id: deadcode
        entry: go tool deadcode -test ./...
        language: system
        pass_filenames: false
