---
- name: Deploy the Shorts application
  hosts: all
  become: true
  gather_facts: true

  vars: # check secrets.yml for others
    service_binary: ../shorts

  tasks:
    - name: Config file is present
      become: true
      copy:
        src: shorts.yml
        dest: /etc/shorts.yml
        mode: '0644'
      register: config_copied
      tags: [ shorts, yaml, config ]

    - name: Service is restarted
      systemd:
        name: shorts.service
        state: restarted
      when: config_copied.changed
      tags: [ systemd, service ]

  roles:
    - role: suhlig.simple_systemd_service
      become: true
      vars:
        program:
          name: shorts
          description: Shorts URL shortener
          binary: "{{ service_binary }}"
          parameters:
            - "-port {{ shorts_port }}"
            - "-urls /etc/shorts.yml"
      tags: [ shorts, url, shortener, systemd, service ]
    - role: suhlig.caddy_reverse_proxy
      become: true
      vars:
        caddy_domain: "{{ shorts_fqdn }}"
        caddy_port: "{{ shorts_port }}"
      tags: [ shorts, url, shortener, caddy, proxy ]
